# Generated by Django 6.0.1 on 2026-01-08 13:55

import django.db.models.deletion
from django.db import migrations, models


def migrate_customer_data(apps, schema_editor):
    License = apps.get_model("license_app", "License")
    Customer = apps.get_model("license_app", "Customer")

    # Create customers from the old CharField
    for customer_name in License.objects.values_list(
        "customer_old", flat=True
    ).distinct():
        if customer_name:
            Customer.objects.get_or_create(name=customer_name)

    # Link licenses to the new Customer objects
    for customer in Customer.objects.all():
        License.objects.filter(customer_old=customer.name).update(customer=customer)


class Migration(migrations.Migration):

    dependencies = [
        ("license_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nom du type de client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de client",
                "verbose_name_plural": "Types de client",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nom du client"),
                ),
                (
                    "client_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="license_app.clienttype",
                        verbose_name="Type de client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.RenameField(
            model_name="license",
            old_name="customer",
            new_name="customer_old",
        ),
        migrations.AddField(
            model_name="license",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="license_app.customer",
                verbose_name="Client",
            ),
        ),
        migrations.RunPython(migrate_customer_data),
        migrations.RemoveField(
            model_name="license",
            name="customer_old",
        ),
        migrations.AlterField(
            model_name="license",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="license_app.customer",
                verbose_name="Client",
            ),
        ),
    ]
