# Generated by Django 6.0.1 on 2026-01-08 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license_app", "0002_clienttype_customer_alter_license_customer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="customers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateurs associés",
            ),
        ),
    ]
