# Generated by Django 6.0.1 on 2026-01-08 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license_app", "0002_clienttype_customer_alter_license_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Catégorie utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie utilisateur",
                "verbose_name_plural": "Catégories utilisateur",
            },
        ),
        migrations.CreateModel(
            name="Editeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Éditeur"
                    ),
                ),
            ],
            options={
                "verbose_name": "Éditeur",
                "verbose_name_plural": "Éditeurs",
            },
        ),
        migrations.CreateModel(
            name="Entite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Entité"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entité",
                "verbose_name_plural": "Entités",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Service"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.RemoveField(
            model_name="license",
            name="comment",
        ),
        migrations.AddField(
            model_name="customer",
            name="email_contact",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email du contact"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="nom_prenom_contact",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Nom et prénom du contact",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="numero_telephone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Numéro de téléphone"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="contact_de_livraison",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Contact de livraison",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="date_de_livraison",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de livraison"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="date_derniere_commande",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Date de dernière commande",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="derniere_commande",
            field=models.CharField(
                default="", max_length=100, verbose_name="Dernière commande"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="donneur_d_ordre",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Donneur d’ordre"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="end_user_declare",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="End user déclaré"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="identifiant_pack",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Identifiant pack"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="marche_hors_marche",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Marché / Hors marché",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="numero_commande_sap",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Numéro de commande SAP",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="numero_ej_bdc",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Numéro EJ / BDC"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="numero_licence_optionnel",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Numéro de licence optionnel (GK, RECON, Sale ID…)",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="numero_rio",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Numéro RIO"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="pack",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Pack"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="remarques",
            field=models.TextField(blank=True, null=True, verbose_name="Remarques"),
        ),
        migrations.AddField(
            model_name="license",
            name="support",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Support (ex : R226)",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="type_de_licence",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Type de licence"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="license_app.customer",
                verbose_name="End user réel",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="expiry_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date d’échéance"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="license_number",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Numéro de licence / dongle"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="license_app.product",
                verbose_name="Produit",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="categorie_utilisateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="license_app.categorieutilisateur",
                verbose_name="Catégorie utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="editeur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="license_app.editeur",
                verbose_name="Éditeur",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="entite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="license_app.entite",
                verbose_name="Entité",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="license_app.service",
                verbose_name="Service",
            ),
        ),
    ]
